#!/bin/bash
CHECKPOINT_PERIOD=2
MODEL=phold_roll
THREAD=8
LP=8
SEC=30
DEBUG=0
VERSION=1
OUTPUT_FILE="results_phold_roll${VERSION}.txt"

echo "make ${MODEL} DEBUG=${DEBUG} ORIGINAL=1 CHECKPOINT_PERIOD=${CHECKPOINT_PERIOD}" >> ${OUTPUT_FILE}
make ${MODEL} DEBUG=${DEBUG} ORIGINAL=1 CHECKPOINT_PERIOD=${CHECKPOINT_PERIOD}
echo ""
./${MODEL} ${THREAD} ${LP} ${SEC} >> ${OUTPUT_FILE}

echo "make ${MODEL} DEBUG=${DEBUG} ORIGINAL=1 PREEMPT_COUNTER=1 CHECKPOINT_PERIOD=${CHECKPOINT_PERIOD}" >> ${OUTPUT_FILE}
make ${MODEL} DEBUG=${DEBUG} ORIGINAL=1 PREEMPT_COUNTER=1 CHECKPOINT_PERIOD=${CHECKPOINT_PERIOD}
echo ""
./${MODEL} ${THREAD} ${LP} ${SEC} >> ${OUTPUT_FILE}

echo "make ${MODEL} DEBUG=${DEBUG} ORIGINAL=1 PREEMPT_COUNTER=1 LONG_JMP=1 CHECKPOINT_PERIOD=${CHECKPOINT_PERIOD}" >> ${OUTPUT_FILE}
make ${MODEL} DEBUG=${DEBUG} ORIGINAL=1 PREEMPT_COUNTER=1 LONG_JMP=1 CHECKPOINT_PERIOD=${CHECKPOINT_PERIOD}
echo ""
./${MODEL} ${THREAD} ${LP} ${SEC} >> ${OUTPUT_FILE}

echo "make ${MODEL} DEBUG=${DEBUG} ORIGINAL=1 PREEMPT_COUNTER=1 LONG_JMP=1 HANDLE_INTERRUPT=1 CHECKPOINT_PERIOD=${CHECKPOINT_PERIOD}" >> ${OUTPUT_FILE}
make ${MODEL} DEBUG=${DEBUG} ORIGINAL=1 PREEMPT_COUNTER=1 LONG_JMP=1 HANDLE_INTERRUPT=1 CHECKPOINT_PERIOD=${CHECKPOINT_PERIOD}
echo ""
./${MODEL} ${THREAD} ${LP} ${SEC} >> ${OUTPUT_FILE}

echo "make ${MODEL} DEBUG=${DEBUG} ORIGINAL=1 PREEMPT_COUNTER=1 LONG_JMP=1 HANDLE_INTERRUPT=1 CHECKPOINT_PERIOD=${CHECKPOINT_PERIOD} INTERRUPT_FORWARD=1 INTERRUPT_SILENT=1" >> ${OUTPUT_FILE}
make ${MODEL} DEBUG=${DEBUG} ORIGINAL=1 PREEMPT_COUNTER=1 LONG_JMP=1 HANDLE_INTERRUPT=1 CHECKPOINT_PERIOD=${CHECKPOINT_PERIOD} INTERRUPT_FORWARD=1 INTERRUPT_SILENT=1
echo ""
./${MODEL} ${THREAD} ${LP} ${SEC} >> ${OUTPUT_FILE}

echo "make ${MODEL} DEBUG=${DEBUG} ORIGINAL=1 PREEMPT_COUNTER=1 LONG_JMP=1 HANDLE_INTERRUPT=1 CHECKPOINT_PERIOD=${CHECKPOINT_PERIOD} INTERRUPT_FORWARD=1 INTERRUPT_SILENT=1 CONSTANT_CHILD_INVALIDATION=1" >> ${OUTPUT_FILE}
make ${MODEL} DEBUG=${DEBUG} ORIGINAL=1 PREEMPT_COUNTER=1 LONG_JMP=1 HANDLE_INTERRUPT=1 CHECKPOINT_PERIOD=${CHECKPOINT_PERIOD} INTERRUPT_FORWARD=1 INTERRUPT_SILENT=1 CONSTANT_CHILD_INVALIDATION=1
echo ""
./${MODEL} ${THREAD} ${LP} ${SEC} >> ${OUTPUT_FILE}

echo "make ${MODEL} DEBUG=${DEBUG} ORIGINAL=1 PREEMPT_COUNTER=1 LONG_JMP=1 HANDLE_INTERRUPT=1 CHECKPOINT_PERIOD=${CHECKPOINT_PERIOD} INTERRUPT_FORWARD=1 INTERRUPT_SILENT=1 CONSTANT_CHILD_INVALIDATION=1 POSTING=1" >> ${OUTPUT_FILE}
make ${MODEL} DEBUG=${DEBUG} ORIGINAL=1 PREEMPT_COUNTER=1 LONG_JMP=1 HANDLE_INTERRUPT=1 CHECKPOINT_PERIOD=${CHECKPOINT_PERIOD} INTERRUPT_FORWARD=1 INTERRUPT_SILENT=1 CONSTANT_CHILD_INVALIDATION=1 POSTING=1
echo ""
./${MODEL} ${THREAD} ${LP} ${SEC} >> ${OUTPUT_FILE}

echo "make ${MODEL} DEBUG=${DEBUG} ORIGINAL=1 PREEMPT_COUNTER=1 LONG_JMP=1 HANDLE_INTERRUPT=1 CHECKPOINT_PERIOD=${CHECKPOINT_PERIOD} INTERRUPT_FORWARD=1 INTERRUPT_SILENT=1 CONSTANT_CHILD_INVALIDATION=1 POSTING=1 IPI_SUPPORT=1" >> ${OUTPUT_FILE}
make ${MODEL} DEBUG=${DEBUG} ORIGINAL=1 PREEMPT_COUNTER=1 LONG_JMP=1 HANDLE_INTERRUPT=1 CHECKPOINT_PERIOD=${CHECKPOINT_PERIOD} INTERRUPT_FORWARD=1 INTERRUPT_SILENT=1 CONSTANT_CHILD_INVALIDATION=1 POSTING=1 IPI_SUPPORT=1
echo ""
./${MODEL} ${THREAD} ${LP} ${SEC} >> ${OUTPUT_FILE}

echo "make ${MODEL} DEBUG=${DEBUG} ORIGINAL=1 PREEMPT_COUNTER=1 LONG_JMP=1 HANDLE_INTERRUPT=1 CHECKPOINT_PERIOD=${CHECKPOINT_PERIOD} INTERRUPT_FORWARD=1 INTERRUPT_SILENT=1 CONSTANT_CHILD_INVALIDATION=1 POSTING=1 IPI_SUPPORT=1 POSTING_SYNC_CHECK_FORWARD=1 POSTING_SYNC_CHECK_SILENT=1" >> ${OUTPUT_FILE}
make ${MODEL} DEBUG=${DEBUG} ORIGINAL=1 PREEMPT_COUNTER=1 LONG_JMP=1 HANDLE_INTERRUPT=1 CHECKPOINT_PERIOD=${CHECKPOINT_PERIOD} INTERRUPT_FORWARD=1 INTERRUPT_SILENT=1 CONSTANT_CHILD_INVALIDATION=1 POSTING=1 IPI_SUPPORT=1 POSTING_SYNC_CHECK_FORWARD=1 POSTING_SYNC_CHECK_SILENT=1
echo ""
./${MODEL} ${THREAD} ${LP} ${SEC} >> ${OUTPUT_FILE}

echo "make ${MODEL} DEBUG=${DEBUG} ORIGINAL=1 PREEMPT_COUNTER=1 LONG_JMP=1 HANDLE_INTERRUPT=1 CHECKPOINT_PERIOD=${CHECKPOINT_PERIOD} INTERRUPT_FORWARD=1 INTERRUPT_SILENT=1 CONSTANT_CHILD_INVALIDATION=1 POSTING=1 POSTING_SYNC_CHECK_FORWARD=1 POSTING_SYNC_CHECK_SILENT=1" >> ${OUTPUT_FILE}
make ${MODEL} DEBUG=${DEBUG} ORIGINAL=1 PREEMPT_COUNTER=1 LONG_JMP=1 HANDLE_INTERRUPT=1 CHECKPOINT_PERIOD=${CHECKPOINT_PERIOD} INTERRUPT_FORWARD=1 INTERRUPT_SILENT=1 CONSTANT_CHILD_INVALIDATION=1 POSTING=1 POSTING_SYNC_CHECK_FORWARD=1 POSTING_SYNC_CHECK_SILENT=1
echo ""
./${MODEL} ${THREAD} ${LP} ${SEC} >> ${OUTPUT_FILE}

#no constant child invalidation

echo "make ${MODEL} DEBUG=${DEBUG} ORIGINAL=1 PREEMPT_COUNTER=1 LONG_JMP=1 HANDLE_INTERRUPT=1 CHECKPOINT_PERIOD=${CHECKPOINT_PERIOD} INTERRUPT_FORWARD=1 INTERRUPT_SILENT=1 POSTING=1" >> ${OUTPUT_FILE}
make ${MODEL} DEBUG=${DEBUG} ORIGINAL=1 PREEMPT_COUNTER=1 LONG_JMP=1 HANDLE_INTERRUPT=1 CHECKPOINT_PERIOD=${CHECKPOINT_PERIOD} INTERRUPT_FORWARD=1 INTERRUPT_SILENT=1 POSTING=1
echo ""
./${MODEL} ${THREAD} ${LP} ${SEC} >> ${OUTPUT_FILE}

echo "make ${MODEL} DEBUG=${DEBUG} ORIGINAL=1 PREEMPT_COUNTER=1 LONG_JMP=1 HANDLE_INTERRUPT=1 CHECKPOINT_PERIOD=${CHECKPOINT_PERIOD} INTERRUPT_FORWARD=1 INTERRUPT_SILENT=1 POSTING=1 IPI_SUPPORT=1" >> ${OUTPUT_FILE}
make ${MODEL} DEBUG=${DEBUG} ORIGINAL=1 PREEMPT_COUNTER=1 LONG_JMP=1 HANDLE_INTERRUPT=1 CHECKPOINT_PERIOD=${CHECKPOINT_PERIOD} INTERRUPT_FORWARD=1 INTERRUPT_SILENT=1 POSTING=1 IPI_SUPPORT=1
echo ""
./${MODEL} ${THREAD} ${LP} ${SEC} >> ${OUTPUT_FILE}

echo "make ${MODEL} DEBUG=${DEBUG} ORIGINAL=1 PREEMPT_COUNTER=1 LONG_JMP=1 HANDLE_INTERRUPT=1 CHECKPOINT_PERIOD=${CHECKPOINT_PERIOD} INTERRUPT_FORWARD=1 INTERRUPT_SILENT=1 POSTING=1 IPI_SUPPORT=1 POSTING_SYNC_CHECK_FORWARD=1 POSTING_SYNC_CHECK_SILENT=1" >> ${OUTPUT_FILE}
make ${MODEL} DEBUG=${DEBUG} ORIGINAL=1 PREEMPT_COUNTER=1 LONG_JMP=1 HANDLE_INTERRUPT=1 CHECKPOINT_PERIOD=${CHECKPOINT_PERIOD} INTERRUPT_FORWARD=1 INTERRUPT_SILENT=1 POSTING=1 IPI_SUPPORT=1 POSTING_SYNC_CHECK_FORWARD=1 POSTING_SYNC_CHECK_SILENT=1
echo ""
./${MODEL} ${THREAD} ${LP} ${SEC} >> ${OUTPUT_FILE}

echo "make ${MODEL} DEBUG=${DEBUG} ORIGINAL=1 PREEMPT_COUNTER=1 LONG_JMP=1 HANDLE_INTERRUPT=1 CHECKPOINT_PERIOD=${CHECKPOINT_PERIOD} INTERRUPT_FORWARD=1 INTERRUPT_SILENT=1 POSTING=1 POSTING_SYNC_CHECK_FORWARD=1 POSTING_SYNC_CHECK_SILENT=1" >> ${OUTPUT_FILE}
make ${MODEL} DEBUG=${DEBUG} ORIGINAL=1 PREEMPT_COUNTER=1 LONG_JMP=1 HANDLE_INTERRUPT=1 CHECKPOINT_PERIOD=${CHECKPOINT_PERIOD} INTERRUPT_FORWARD=1 INTERRUPT_SILENT=1 POSTING=1 POSTING_SYNC_CHECK_FORWARD=1 POSTING_SYNC_CHECK_SILENT=1
echo ""
./${MODEL} ${THREAD} ${LP} ${SEC} >> ${OUTPUT_FILE}