#!/bin/bash

MODEL=$1
THREAD=$2
LP=$3
SEC=$4
CHECKPOINT_PERIOD=$5
VERSION=$6

OUTPUT_FILE="results/results_${MODEL}${VERSION}.txt"

echo "make ${MODEL} CHECKPOINT_PERIOD=${CHECKPOINT_PERIOD}" >> ${OUTPUT_FILE}
make ${MODEL} CHECKPOINT_PERIOD=${CHECKPOINT_PERIOD}
echo "test1"
./${MODEL} ${THREAD} ${LP} ${SEC} >> ${OUTPUT_FILE}
echo "test2"
./${MODEL} ${THREAD} ${LP} ${SEC} >> ${OUTPUT_FILE}

echo "make ${MODEL} POSTING=1 IPI_SUPPORT=1 CHECKPOINT_PERIOD=${CHECKPOINT_PERIOD}" >> ${OUTPUT_FILE}
make ${MODEL} POSTING=1 IPI_SUPPORT=1 CHECKPOINT_PERIOD=${CHECKPOINT_PERIOD}
echo "test3"
./${MODEL} ${THREAD} ${LP} ${SEC} >> ${OUTPUT_FILE}
echo "test4"
./${MODEL} ${THREAD} ${LP} ${SEC} >> ${OUTPUT_FILE}